console.log("hello word")
console.log("hi")
console.log("welcome")
console.log("my hours")

console.log("how are you")
console.log("I'm fine")
console.log("I have to go")
console.log("I would like to eat")
console.log("I'm afraid")