console.log("hello word")
console.log("hi")
console.log("welcome")
console.log("my hours")

console.log("how are you")
console.log("I'm fine")
console.log("I have to go")
console.log("I would like to eat")
console.log("I'm afraid")
console.log("check ")
console.log("next")
console.log("I am busy today")
console.log("I have come to visit doctor ")
console.log("I'm a ielts candidate ")
console.log("he")